"use client";
import {useEffect,useState,useRef} from "react";
import {assignments,practiceCase,teamCase,scenario,teamEvidence,validAwards,CONSENT_VERSION} from "../lib/experiment";
import {optionalItems} from "../lib/consent";
import {Allocation,Consent,Results,Prompts,Field} from "./ui";
type Access={code:string;token:string};
const empty=()=>["","","",""];
const noSurvey={income:null,rewards:null,politics:null,gender:null};
const complete=(v:string[])=>v.every(x=>x!=="")&&validAwards(v.map(Number));
const stages=["Welcome","Individual","Results & discussion","Presentations","Wrap-up"];
export default function Page(){
 const [access,setAccess]=useState<Access|null>(null),[s,setS]=useState<any>(null),[code,setCode]=useState(""),[team,setTeam]=useState(1),[consent,setConsent]=useState(false),[teacher,setTeacher]=useState(false),[key,setKey]=useState(""),[title,setTitle]=useState("Motivation & Allocation"),[teams,setTeams]=useState(11),[demo,setDemo]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[loaded,setLoaded]=useState(false);
 const [v,setV]=useState<string[]>(empty),[quiz,setQuiz]=useState({department:"",total:"",self:""}),[survey,setSurvey]=useState<any>(noSurvey),[reason,setReason]=useState(""),[needed,setNeeded]=useState(""),[teamKey,setTeamKey]=useState(""),[tv,setTv]=useState<string[]>(empty),[draft,setDraft]=useState({pattern:"",explanation:"",need:"",actions:"",principle:""}),[offline,setOffline]=useState(false),[oi,setOi]=useState(0);
 const started=useRef(Date.now());
 const req=async(body?:any,a=access)=>{const r=await fetch(body?"/api/classroom":"/api/classroom?code="+encodeURIComponent(a?.code||""),{method:body?"POST":"GET",headers:{"Content-Type":"application/json","x-class-token":a?.token||""},body:body?JSON.stringify({...body,code:body.code??a?.code}):undefined,cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.error||"Please try again.");return x;};
 const hydrate=(x:any)=>{setS(x);if(x.me?.submitted){setSurvey(x.me.survey||noSurvey);setReason(x.me.reflection?.reason||"");setNeeded(x.me.reflection?.needed||"");}};
 const restoreTeam=(x:any)=>{const own=x.teams?.find((t:any)=>t.team===x.me?.team)?.payload;if(own){setDraft({pattern:own.pattern,explanation:own.explanation,need:own.need,actions:own.actions,principle:own.principle});setTv(own.awards.map(String));}};
 useEffect(()=>{const u=new URL(location.href),q=u.searchParams.get("code");setCode(q||"");setTeacher(u.searchParams.has("teacher"));try{const raw=localStorage.getItem("ob-vercel-access");if(raw){const a=JSON.parse(raw);if(!q||q===a.code){setAccess(a);req(undefined,a).then(x=>{hydrate(x);restoreTeam(x);}).catch(e=>setMsg(e.message));}}}catch{}setLoaded(true);},[]);
 useEffect(()=>{if(!access)return;const t=setInterval(()=>req().then(hydrate).catch(e=>setMsg(e.message)),15000);return()=>clearInterval(t);},[access]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMsg("");try{await fn();}catch(e:any){setMsg(e.message||"Please try again.");}finally{setBusy(false);}};
 const connect=(create=false)=>run(async()=>{const x=await req(create?{action:"create",hostKey:key,title,teamCount:teams,demo}:{action:"join",code:code.trim().toUpperCase(),team,consent,consentVersion:CONSENT_VERSION});const a={code:x.room.code,token:x.credential};localStorage.setItem("ob-vercel-access",JSON.stringify(a));setAccess(a);hydrate(x);setKey("");setV(empty());});
 const next=()=>run(async()=>{if(s.room.phase===1&&!confirm("Close individual responses and share class results?"))return;if(s.room.phase===2&&!confirm("Close team submissions and start presentations?"))return;hydrate(await req({action:"phase",phase:s.room.phase+1}));});
 const prepare=()=>run(async()=>{const x=await req({action:"prepare",awards:v.map(Number),department:quiz.department,total:+quiz.total,self:quiz.self});hydrate(x);setMsg(x.feedback);if(x.me.prepared){setV(empty());started.current=Date.now();}});
 const save=()=>run(async()=>{hydrate(await req({action:"round",index:s.me.answers.length,awards:v.map(Number),elapsedMs:Date.now()-started.current}));setV(empty());started.current=Date.now();});
 const finish=(skip=false)=>run(async()=>hydrate(await req({action:"finish",survey:skip?noSurvey:survey,reason,needed})));
 const leave=()=>{localStorage.removeItem("ob-vercel-access");setAccess(null);setS(null);setOffline(false);setSurvey(noSurvey);setReason("");setNeeded("");setConsent(false);};
 const withdraw=()=>run(async()=>{if(!confirm("Withdraw and remove your individual answers from the active dataset and class summary?"))return;await req({action:"withdraw"});leave();setMsg("You have withdrawn. Contact the researchers about previously downloaded copies.");});
 const exportData=()=>run(async()=>{const x=await req({action:"export"}),u=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download="OB_"+s.room.code+"_responses.json";a.click();URL.revokeObjectURL(u);});
 const submitTeam=()=>run(async()=>{hydrate(await req({action:"team",teamKey,payload:{...draft,awards:tv.map(Number)}}));setMsg("Team response saved. You can revise it until presentations begin.");});
 const p=s?.room.phase,me=s?.me,host=s?.isHost;
 if(!loaded)return <main>Loading classroom…</main>;
 return <><header><a className="brand" href="/">OB <span>DECISION STUDIO</span></a><span className="course">ORGANIZATIONAL BEHAVIOR / MOTIVATION</span><button className="quiet" onClick={()=>{if(access||offline){if(confirm("Leave this screen? Keep your response reference if you may want to withdraw later."))leave();}else setTeacher(!teacher);}}>{access||offline?"Leave screen":teacher?"Student entry":"Instructor"}</button></header>
 {msg&&<div className="notice" role="status">{msg}<button className="quiet" onClick={()=>setMsg("")}>Dismiss</button></div>}
 {!s&&!offline?<main className="entry"><section className="intro"><div className="eyebrow">THINK / ALLOCATE / DISCUSS</div><h1>Same information.<br/><em>Different decisions.</em></h1><p>Make your own bonus decisions. Explore the class results. Build an explanation together.</p><div className="flow"><span>01 Individual choices</span><span>02 Class results</span><span>03 Team discussion</span></div><p className="small">A classroom pilot after your motivation lecture. Allow about 15–20 minutes individually, followed by team discussion.</p><button className="outline" onClick={()=>{setOffline(true);setV(empty());setOi(0);}}>Try without saving</button></section>
 {teacher?<section className="card"><div className="eyebrow">INSTRUCTOR</div><h2>Open a classroom</h2><label>Class title<input value={title} maxLength={80} onChange={e=>setTitle(e.target.value)}/></label><label>Number of teams<input type="number" min={1} max={22} value={teams} onChange={e=>setTeams(+e.target.value)}/></label><label>Instructor key<input type="password" autoComplete="current-password" value={key} onChange={e=>setKey(e.target.value)}/></label><label className="check"><input type="checkbox" checked={demo} onChange={e=>setDemo(e.target.checked)}/>Rehearsal class (marked as demo)</label><button disabled={busy||!key} onClick={()=>connect(true)}>Create classroom</button><p className="small">For 66 students, 11 teams of 6 is an option. Use your actual class groups.</p></section>:<section className="card"><div className="eyebrow">VOLUNTARY PARTICIPATION</div><h2>Before you join</h2><Consent/><label>Class code<input placeholder="From your instructor" maxLength={8} value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>Team number<input type="number" min={1} max={22} value={team} onChange={e=>setTeam(+e.target.value)}/></label><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I have read the information and voluntarily agree to participate and have my responses stored for the purposes described.</label><button disabled={busy||!consent||code.length!==8} onClick={()=>connect()}>I agree — join the activity</button><button className="quiet" onClick={()=>{setOffline(true);setV(empty());setOi(0);}}>I do not agree — use the no-record activity</button></section>}</main>
 :offline?<main className="narrow"><div className="eyebrow">NO-RECORD ACTIVITY</div><h1>Your choices stay on this screen.</h1><p>No consent, political questions, or server submission are required. Closing or refreshing clears this activity.</p>{oi<8?<section className="card"><h2>Decision {oi+1} of 8</h2><p>{scenario}</p><p>You belong to Department A.</p><Allocation rows={assignments(928)[oi].recipients} department="A" values={v} setValues={setV}/><button disabled={!complete(v)} onClick={()=>{setOi(oi+1);setV(empty());}}>Next decision</button></section>:<section className="card"><h2>Individual activity complete.</h2><p>Your choices were not uploaded. Join your team to discuss the projected class results.</p><Prompts/><button className="outline" onClick={()=>window.print()}>Print prompts</button></section>}</main>
 :<main><div className="heading"><div><div className="eyebrow">{s.room.demo?"REHEARSAL — MAY INCLUDE SYNTHETIC DATA":"CLASSROOM"} · {s.room.code}</div><h1>{s.room.title}</h1></div>{host?<div className="buttons"><button className="outline" onClick={()=>run(async()=>{await navigator.clipboard.writeText(location.origin+"?code="+s.room.code);setMsg("Student link copied.");})}>Copy student link</button><button className="quiet" onClick={()=>run(async()=>hydrate(await req()))}>Refresh counts</button></div>:<span className="tag">Team {me.team} · Department {me.department}</span>}</div>
 <nav className="stages" aria-label="Class stages">{stages.map((x,i)=><span key={x} className={p===i?"active":p>i?"done":""}>{String(i+1).padStart(2,"0")} {x}</span>)}</nav>
 {host&&<section className="teacherbar"><div><strong>{s.counts.completed} / {s.counts.joined}</strong> individual responses completed</div><div className="buttons">{p<4&&<button disabled={busy} onClick={next}>{["Open individual responses","Close responses & share results","Close discussion & present","Finish presentations"][p]}</button>}{p>=2&&<button className="outline" onClick={exportData}>Export research data</button>}</div></section>}
 {p===0&&<section className="card narrow"><div className="eyebrow">THE BRIEF</div><h2>A fixed bonus. Your decision.</h2><p>{scenario}</p><p>Decide independently first. Class results appear after individual responses close. Then discuss them with your team.</p><p>No single allocation is marked as correct. Explain your judgment.</p>{!host&&<p className="waiting">Wait for your instructor to open the activity.</p>}{host&&s.room.demo&&<button className="outline" disabled={busy} onClick={()=>run(async()=>hydrate(await req({action:"demoFill"})))}>Add 66 synthetic responses for rehearsal</button>}</section>}
 {p===1&&(host?<section className="card"><h2>Let students decide independently.</h2><p>Students complete practice, eight decisions, and a final submission. All opinion and background questions are optional. Wait until responses close before discussing allocation rules.</p><p>Students who decline consent can use the no-record activity and join the team discussion.</p></section>:me.submitted?<section className="card narrow"><div className="eyebrow">SUBMITTED</div><h2>Your decisions are saved.</h2><p>Results will appear when your instructor closes individual responses.</p></section>:!me.prepared?<section className="card narrow"><div className="eyebrow">PRACTICE</div><h2>Try the input first.</h2><p>{scenario}</p><p><strong>You belong to Department {me.department}.</strong></p><Allocation rows={practiceCase} department={me.department} values={v} setValues={setV}/><div className="form-grid"><label>My assigned department<select value={quiz.department} onChange={e=>setQuiz({...quiz,department:e.target.value})}><option value="">Select</option><option>A</option><option>B</option></select></label><label>Total bonus<select value={quiz.total} onChange={e=>setQuiz({...quiz,total:e.target.value})}><option value="">Select</option><option value="100">100 points</option><option value="400">400 points</option></select></label><label>Can I award myself points?<select value={quiz.self} onChange={e=>setQuiz({...quiz,self:e.target.value})}><option value="">Select</option><option value="none">No — only the four recipients</option><option value="yes">Yes — I can award myself points</option></select></label></div><button disabled={busy||!complete(v)} onClick={prepare}>Check and begin</button></section>:me.answers.length<8?<section className="card narrow"><div className="eyebrow">INDIVIDUAL DECISION {me.answers.length+1} / 8</div><h2>Divide the 100-point bonus.</h2><p>Your department is <strong>{me.department}</strong>. You receive no share. Each case concerns a new project.</p><details><summary>Review instructions</summary><p>{scenario}</p></details><Allocation rows={me.trials[me.answers.length].recipients} department={me.department} values={v} setValues={setV}/><button disabled={busy||!complete(v)} onClick={save}>{busy?"Saving…":me.answers.length===7?"Save & continue":"Save & next decision"}</button><p className="small">Saved decisions cannot be revised after moving on.</p></section>:<section className="card narrow"><div className="eyebrow">FINAL STEP / OPTIONAL QUESTIONS</div><h2>Your views and feedback</h2><p>Skip any question or all of them. Unanswered items are not treated as neutral. These answers are not shown to classmates.</p><Field label="What information mattered most in your decisions?" value={reason} setValue={setReason}/><Field label="What information or instructions were missing?" value={needed} setValue={setNeeded}/>
 {optionalItems.map(item=><label className="scale" key={item.key}><strong>{item.label}</strong><span>{item.question}</span><div className="anchors"><span>1 — {item.low}</span><span>10 — {item.high}</span></div><select value={survey[item.key]??""} onChange={e=>setSurvey({...survey,[item.key]:e.target.value===""?null:+e.target.value})}><option value="">Prefer not to answer / Skip</option>{Array.from({length:10},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>)}
 <label>Gender (optional)<select value={survey.gender??""} onChange={e=>setSurvey({...survey,gender:e.target.value||null})}><option value="">Prefer not to answer / Skip</option><option value="male">Male</option><option value="female">Female</option><option value="another">Another gender</option></select></label><p className="small">Political orientation is sensitive and optional. You do not have to disclose it to participate.</p><div className="buttons"><button disabled={busy} onClick={()=>finish()}>Submit my responses</button><button className="outline" disabled={busy} onClick={()=>finish(true)}>Skip opinion & background questions and submit</button></div></section>)}
 {p>=2&&<Results stats={s.stats} demo={s.room.demo}/>}
 {p===2&&<section><div className="heading"><div><div className="eyebrow">FROM RESULTS TO REASONS</div><h2>What might explain this pattern?</h2></div><button className="outline" onClick={()=>window.print()}>Print results & prompts</button></div><Prompts/><div className="card"><h3>New information for discussion</h3><p>{teamEvidence}</p><p><strong>All teams now act as the manager of Department A.</strong> Team answers are stored separately from individual answers.</p></div>
 {host?<section className="card"><h3>Representative codes</h3><p>Give each code only to its team representative.</p><div className="team-codes">{s.teamKeys.map((k:string,i:number)=><div key={i}>Team {i+1}<code>{k}</code></div>)}</div><p>{s.teams.length} / {s.room.teamCount} team responses submitted</p></section>:<section className="card"><h3>Team {me.team}: discussion response</h3>{!me.submitted&&<p>A team member who finished the individual task can submit for your team.</p>}{Object.entries({pattern:"1. Which class pattern stands out? Cite a number.",explanation:"2. What could explain it? Give an alternative explanation.",need:"3. Connect the members' statements to a motivation theory. What remains unknown?",actions:"4. Propose two management actions beyond pay. Explain why."}).map(([k,label])=><Field key={k} label={label} value={(draft as any)[k]} setValue={x=>setDraft({...draft,[k]:x})}/>)}<h3>Agree on a team allocation</h3><Allocation rows={teamCase} department="A" values={tv} setValues={setTv}/><Field label="5. State your allocation principle and reasons." value={draft.principle} setValue={x=>setDraft({...draft,principle:x})}/><label>Representative code<input value={teamKey} onChange={e=>setTeamKey(e.target.value)} autoComplete="off"/></label><button disabled={busy||!me.submitted||!complete(tv)} onClick={submitTeam}>Save team response</button>{s.teams.some((t:any)=>t.team===me.team)&&<p className="small">A response is saved. New submissions replace this team's response only.</p>}</section>}</section>}
 {p>=3&&<section><div className="eyebrow">TEAM PRESENTATIONS</div><h2>From a pattern to a proposal.</h2>{s.teams.length?s.teams.map((t:any)=><article className="card" key={t.team}><h3>Team {t.team}</h3><p><b>Observed pattern:</b> {t.payload.pattern}</p><p><b>Explanation:</b> {t.payload.explanation}</p><p><b>Motivation theory:</b> {t.payload.need}</p><p><b>Management actions:</b> {t.payload.actions}</p><p><b>Allocation:</b> {t.payload.awards.map((x:number,i:number)=>teamCase[i].id+": "+x).join(" · ")}</p><p><b>Principle:</b> {t.payload.principle}</p></article>):<p>No team responses submitted.</p>}<div className="card takeaway"><h3>A reward decision is not a measure of motivation.</h3><p>Allocations show how we divided rewards. They do not show how recipients would respond. We also need evidence about what recipients value and how they interpret the decision.</p><p>These results describe voluntary student responses after instruction. Individual and team differences do not establish a causal effect of discussion.</p></div></section>}
 {!host&&<details className="participant-options"><summary>Participation information & withdrawal</summary><Consent/><p>Your response reference: <code>{me.id}</code>. Keep this reference to contact the researchers about your data.</p><button className="outline danger" disabled={busy} onClick={withdraw}>Withdraw and remove my individual responses</button></details>}
 </main>}
 <footer><span>OB DECISION STUDIO</span><span>Individual choices · Shared evidence · Team discussion</span></footer></>;
}
