"use client";
import {useEffect,useState,useRef} from "react";
import {assignments,practiceCase,teamCase,scenario,teamEvidence,CONSENT_VERSION} from "../lib/experiment";
import {normalizeClassCode} from "../lib/class-code";
import {optionalItems} from "../lib/consent";
import {Allocation,Consent,Results,Prompts,Field} from "./ui";
type Access={code:string;token:string;host:boolean};
const empty=()=>["","","","",""];
const noSurvey=()=>({income:null,rewards:null,politics:null,gender:null});
const accessKey=(host:boolean)=>"ob-study2-v8-"+(host?"host":"student")+"-access";
const stages=["Welcome","Individual","Results & discussion","Presentations","Wrap-up"];
const checkItems=[
 ["scoreMeaning","What do the contribution scores represent?"],
 ["ownDepartment","Which department were you assigned in the second part?"],
 ["otherDepartment","Which was the other department?"],
 ["equalStanding","How did the standing of the two departments compare?"],
 ["discretion","How much freedom did you feel you had in choosing the allocations?"],
 ["repetition","Did any cases seem similar or repeated?"],
 ["expectation","What do you think the activity was examining?"],
 ["relationships","Did department information suggest anything else about the members' relationships, responsibilities, or future cooperation?"]
];
export default function Page(){
 const [access,setAccess]=useState<Access|null>(null),[s,setS]=useState<any>(null),[code,setCode]=useState(""),[team,setTeam]=useState(1),[consent,setConsent]=useState(false),[teacher,setTeacher]=useState(false),[key,setKey]=useState(""),[title,setTitle]=useState("Motivation & Allocation"),[teams,setTeams]=useState(11),[demo,setDemo]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[loaded,setLoaded]=useState(false),[pollingPaused,setPollingPaused]=useState(false);
 const [v,setV]=useState(empty),[ready,setReady]=useState(false),[quiz,setQuiz]=useState({total:"",self:""}),[survey,setSurvey]=useState<any>(noSurvey),[question,setQuestion]=useState(0),[reasonText,setReasonText]=useState(""),[checkStep,setCheckStep]=useState(0),[checks,setChecks]=useState<Record<string,string>>({}),[needed,setNeeded]=useState("");
 const [teamKey,setTeamKey]=useState(""),[tv,setTv]=useState(empty),[teamReady,setTeamReady]=useState(false),[draft,setDraft]=useState<Record<string,string>>({pattern:"",explanation:"",need:"",actions:"",principle:""}),[teamStep,setTeamStep]=useState(0);
 const [offline,setOffline]=useState(false),[oi,setOi]=useState(0),[offlineIntro,setOfflineIntro]=useState(false),[offlineTrials]=useState(()=>assignments(928,0));
 const started=useRef(Date.now()),generation=useRef(0),mutating=useRef(false),stateRef=useRef<any>(null);
 const req=async(body?:any,a=access)=>{const r=await fetch(body?"/api/classroom":"/api/classroom?code="+encodeURIComponent(a?.code||""),{method:body?"POST":"GET",headers:{"Content-Type":"application/json","x-class-token":a?.token||""},body:body?JSON.stringify({...body,code:body.code??a?.code}):undefined,cache:"no-store"});const x=await r.json();if(!r.ok){if(r.status===503||r.status===429)setPollingPaused(true);if(x.code==="SESSION_ENDED"&&a&&!a.host){const ended=await req(undefined,a);hydrate(ended);}throw new Error(x.error||"Please try again.");}return x;};
 const hydrate=(x:any)=>{const prev=stateRef.current;if(prev?.room.code===x.room.code&&prev.room.sessionsEndedAt&&!x.room.sessionsEndedAt)return;if(prev?.room.code===x.room.code&&prev?.me?.id===x.me?.id&&(x.me?.revision??0)<(prev?.me?.revision??0))return;stateRef.current=x;setS(x);};
 useEffect(()=>{const u=new URL(location.href),q=normalizeClassCode(u.searchParams.get("code")||""),isTeacher=u.searchParams.has("teacher");setCode(q);setTeacher(isTeacher);try{const raw=localStorage.getItem(accessKey(isTeacher));if(raw){const a=JSON.parse(raw);if(!q||q===a.code){setAccess(a);const rev=++generation.current;req(undefined,a).then(x=>{if(rev===generation.current)hydrate(x);}).catch(e=>setMsg(e.message));}}}catch{}setLoaded(true);},[]);
 useEffect(()=>{if(!access||access.host||pollingPaused||s?.room.sessionsEndedAt||s?.room.phase===4)return;let active=true;const refresh=async()=>{if(mutating.current||document.hidden)return;const rev=++generation.current;try{const x=await req(undefined,access);if(active&&!mutating.current&&rev===generation.current)hydrate(x);}catch(e:any){if(active&&rev===generation.current)setMsg(e.message);}};const timer=setInterval(refresh,s?.room.phase===0?5000:15000);return()=>{active=false;clearInterval(timer);generation.current++;};},[access,s?.room.phase,s?.room.sessionsEndedAt,pollingPaused]);
 const run=async(fn:()=>Promise<void>)=>{if(mutating.current)return;mutating.current=true;generation.current++;setBusy(true);setMsg("");try{await fn();}catch(e:any){setMsg(e.message||"Please try again.");}finally{generation.current++;mutating.current=false;setBusy(false);}};
 const connect=(create=false)=>run(async()=>{const x=await req(create?{action:"create",hostKey:key,title,teamCount:teams,demo}:{action:"join",code:normalizeClassCode(code),team,consent,consentVersion:CONSENT_VERSION});const a={code:x.room.code,token:x.credential,host:create};localStorage.setItem(accessKey(create),JSON.stringify(a));history.replaceState(null,"",create?"?teacher=1":"?code="+a.code);setAccess(a);hydrate(x);setKey("");setV(empty());setReady(false);setQuestion(0);});
 const leave=()=>{generation.current++;if(access)localStorage.removeItem(accessKey(access.host));setAccess(null);setS(null);stateRef.current=null;setPollingPaused(false);setOffline(false);setSurvey(noSurvey());setConsent(false);setV(empty());setReady(false);setQuestion(0);setReasonText("");setCheckStep(0);setChecks({});setNeeded("");};
 const refresh=()=>run(async()=>{setPollingPaused(false);hydrate(await req());});
 const next=()=>run(async()=>{if(s.room.phase===1&&!confirm("Close individual responses and share class results?"))return;if(s.room.phase===2&&!confirm("Close team submissions and start presentations?"))return;hydrate(await req({action:"phase",phase:s.room.phase+1}));});
 const endSessions=()=>run(async()=>{if(!confirm("End all student sessions for this class? Students will stop at their next status check and cannot rejoin. Saved responses remain available for export; unsaved entries will be lost. This cannot be reopened."))return;hydrate(await req({action:"endSessions"}));setMsg("All student sessions ended. Saved responses remain available for export.");});
 const baseline=()=>run(async()=>hydrate(await req({action:"baseline",survey})));
 const prepare=()=>run(async()=>{const x=await req({action:"prepare",awards:v.map(Number),total:+quiz.total,self:quiz.self});hydrate(x);setMsg(x.feedback||"");if(x.me.prepared){setV(empty());setReady(false);started.current=Date.now();}});
 const beginB=()=>run(async()=>{hydrate(await req({action:"beginB"}));setV(empty());setReady(false);started.current=Date.now();});
 const save=()=>run(async()=>{hydrate(await req({action:"round",index:s.me.answers.length,awards:v.map(Number),elapsedMs:Date.now()-started.current}));setV(empty());setReady(false);started.current=Date.now();});
 const finish=()=>run(async()=>hydrate(await req({action:"finish",checks,needed})));
 const exportData=()=>run(async()=>{const x=await req({action:"export"}),u=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download="Study2_v8_classroom_"+s.room.code+".json";a.click();URL.revokeObjectURL(u);});
 const withdraw=()=>run(async()=>{if(!confirm("Withdraw and remove your individual answers from the active dataset and class summary?"))return;await req({action:"withdraw"});leave();setMsg("Your individual responses have been withdrawn.");});
 const submitTeam=()=>run(async()=>{hydrate(await req({action:"team",teamKey,payload:{...draft,awards:tv.map(Number)}}));setMsg("Team response saved. You can revise it until presentations begin.");});
 const p=s?.room.phase,me=s?.me,host=s?.isHost;
 const order=["politics",...(me?.surveyOrder||["income","rewards"]),"gender"],item=optionalItems.find(x=>x.key===order[question]);
 const reasonIndex=me?.reasons?.findIndex((x:any)=>x.initial===null||x.followup===null)??-1,reasonRecord=reasonIndex>=0?me.reasons[reasonIndex]:null,reasonCase=reasonIndex>=0?me.reasonCases?.[reasonIndex]:null;
 const teamFields=[["pattern","Which class pattern stands out? Cite a number."],["explanation","What could explain it? Give an alternative explanation."],["need","Connect the members' statements to a motivation theory. What remains unknown?"],["actions","Propose two management actions beyond pay. How would you check their effects?"]];
 if(!loaded)return <main>Loading classroom…</main>;
 return <><header><a className="brand" href="/">OB <span>DECISION STUDIO</span></a><span className="course">ORGANIZATIONAL BEHAVIOR / MOTIVATION</span>{access||offline?<button className="quiet" onClick={()=>{if(confirm("Leave this screen? Keep your response reference if needed."))leave();}}>Leave screen</button>:<a href={teacher?"/":"?teacher=1"}>{teacher?"Student entry":"Instructor"}</a>}</header>
 {msg&&<div className="notice" role="status"><span>{msg}</span><button className="quiet" onClick={()=>setMsg("")}>Dismiss</button></div>}
 {!s&&!offline?<main className="entry"><section className="intro"><div className="eyebrow">THINK / ALLOCATE / DISCUSS</div><h1>Same information.<br/><em>Different decisions.</em></h1><p>Allocate a 1,000-unit bonus among yourself and four project members. Make 12 decisions, one person at a time.</p><div className="flow"><span>01 Individual decisions</span><span>02 Class results</span><span>03 Team discussion</span></div><button className="outline" onClick={()=>{setOffline(true);setV(empty());setReady(false);setOi(0);setOfflineIntro(false);}}>Try without saving</button></section>
 {teacher?<section className="card"><div className="eyebrow">INSTRUCTOR · STUDY 2 v8 TASK</div><h2>Create a classroom</h2><p>5 recipients · 1,000 units · 4 cases without departments + 8 with departments.</p><p className="small">Same-day classroom adaptation. No monetary payments. Create a new classroom for this version; earlier response records remain separate.</p><label>Class title<input value={title} maxLength={80} onChange={e=>setTitle(e.target.value)}/></label><label>Number of teams<input type="number" min={1} max={22} value={teams} onChange={e=>setTeams(+e.target.value)}/></label><label>Instructor key<input type="password" autoComplete="current-password" value={key} onChange={e=>setKey(e.target.value)}/></label><label className="check"><input type="checkbox" checked={demo} onChange={e=>setDemo(e.target.checked)}/>Rehearsal classroom</label><button disabled={busy||!key} onClick={()=>connect(true)}>Create classroom</button></section>:<section className="card"><h2>Before you join</h2><Consent/><label>Class code<input placeholder="8-character code from your instructor" value={code} onChange={e=>setCode(normalizeClassCode(e.target.value))}/></label><label>Team number<input type="number" min={1} max={22} value={team} onChange={e=>setTeam(+e.target.value)}/></label><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I have read the information and voluntarily agree to participate and have my responses stored.</label><button disabled={busy||!consent||!/^[A-F0-9]{8}$/.test(code)} onClick={()=>connect()}>I agree — join the activity</button><button className="quiet" onClick={()=>{setOffline(true);setV(empty());setReady(false);setOi(0);setOfflineIntro(false);}}>I do not agree — use the no-record activity</button></section>}</main>
 :offline?<main className="narrow"><div className="eyebrow">NO-RECORD ACTIVITY</div><p>Your decisions stay on this screen and are cleared when you leave or refresh.</p>{oi===4&&!offlineIntro?<section className="card"><h2>Departments in the next cases</h2><p>You belong to Department A. Two other members share your department and two belong to B. Both departments have equal standing.</p><button onClick={()=>setOfflineIntro(true)}>Continue to part 2</button></section>:oi<12?<section className="card"><h2>Decision {oi+1} of 12</h2><p>{scenario}</p><Allocation key={"offline"+oi} rows={offlineTrials[oi].recipients} department={oi>=4?"A":null} values={v} setValues={setV} onReady={setReady}/><button disabled={!ready} onClick={()=>{setOi(oi+1);setV(empty());setReady(false);}}>Next decision</button></section>:<section className="card"><h2>Individual activity complete.</h2><p>No responses were uploaded. You can join your team's discussion.</p><Prompts/></section>}</main>
 :s.sessionEnded?<main className="narrow"><section className="card"><div className="eyebrow">CLASS {s.room.code}</div><h1>Session ended</h1><p>Your instructor has ended student access to this class. Automatic updates have stopped.</p><p>Your previously saved responses are retained. Entries that were not saved were not submitted.</p><button onClick={leave}>Leave screen</button><details className="participant-options"><summary>Participation information & withdrawal</summary><Consent/><button className="outline danger" disabled={busy} onClick={withdraw}>Withdraw and remove my individual responses</button></details></section></main>:<main><div className="heading"><div><div className="eyebrow">{s.room.demo?"REHEARSAL":"CLASSROOM"} · {s.room.code}</div><h1>{s.room.title}</h1></div>{host?<div className="buttons"><button className="outline" onClick={()=>run(async()=>{await navigator.clipboard.writeText(s.room.code);setMsg("Class code copied: "+s.room.code);})}>Copy class code</button><button className="quiet" disabled={busy} onClick={refresh}>Refresh counts</button></div>:<div><span className="tag">Team {me.team}{me.department?" · Department "+me.department:""}</span>{p>0&&p<4&&<button className="quiet" disabled={busy} onClick={refresh}>Refresh activity</button>}{pollingPaused&&<p role="status" className="small">Automatic updates are paused. Refresh manually when storage is available.</p>}</div>}</div>
 <nav className="stages" aria-label="Class stages">{stages.map((x,i)=><span key={x} className={p===i?"active":p>i?"done":""}>{String(i+1).padStart(2,"0")} {x}</span>)}</nav>
 {host&&<section className="teacherbar"><div><strong>{s.counts.completed} / {s.counts.joined}</strong> individual responses completed</div><div className="buttons">{p<4&&!s.room.sessionsEndedAt&&<button disabled={busy} onClick={next}>{["Open individual responses","Close responses & share results","Close discussion & present","Finish presentations"][p]}</button>}{p>=2&&<button className="outline" disabled={busy} onClick={exportData}>Export response data</button>}{!s.room.sessionsEndedAt?<button className="outline danger" disabled={busy} onClick={endSessions}>End all student sessions</button>:<span role="status">All student sessions ended</span>}</div></section>}
 {p===0&&<section className="card narrow"><h2>A fixed bonus. Your decision.</h2><p>{scenario}</p>{host?<p className="waiting">Copy the class code for your students, then click “Open individual responses”.</p>:<div className="waiting"><p>You have joined successfully. Your instructor needs to open individual responses. This screen checks automatically every 5 seconds.</p><button className="outline" disabled={busy} onClick={refresh}>Check activity status</button></div>}</section>}
 {p===1&&(host?<section className="card"><h2>Let students decide independently.</h2><p>Students answer or skip pre-activity questions, practise entering amounts, and complete 12 decisions. Department information appears only after their first four decisions.</p><p>Keep this stage open until final submissions are saved. Classroom records are labelled separately from the formal two-session Study 2 protocol.</p></section>:me.submitted?<section className="card narrow"><div className="eyebrow">SUBMITTED</div><h2>Your decisions are saved.</h2><p>All 12 decisions are stored. Results appear when your instructor closes individual responses.</p></section>:!me.preSurveyDone?<section className="card narrow"><div className="eyebrow">BEFORE THE ACTIVITY · OPTIONAL {question+1} / 4</div><h2>{item?.label||"Gender"}</h2><p>You may skip any question. These answers are not shown to classmates.</p>{item?<label className="scale"><strong>{item.question}</strong><div className="anchors"><span>1 — {item.low}</span><span>10 — {item.high}</span></div><select aria-label={item.label} value={survey[item.key]??""} onChange={e=>setSurvey({...survey,[item.key]:e.target.value===""?null:+e.target.value})}><option value="">Prefer not to answer / Skip</option>{Array.from({length:10},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>:<label>Gender (optional)<select value={survey.gender??""} onChange={e=>setSurvey({...survey,gender:e.target.value||null})}><option value="">Prefer not to answer / Skip</option><option value="male">Male</option><option value="female">Female</option><option value="another">Another gender</option></select></label>}<div className="buttons">{question>0&&<button className="outline" onClick={()=>setQuestion(question-1)}>Previous question</button>}<button disabled={busy} onClick={()=>question<3?setQuestion(question+1):baseline()}>{question<3?"Continue":"Save pre-activity answers"}</button></div></section>
 :!me.prepared?<section className="card narrow"><div className="eyebrow">PRACTICE · NOT ONE OF THE 12 DECISIONS</div><h2>Try the input first.</h2><p>{scenario}</p><Allocation key="practice" rows={practiceCase} department={null} values={v} setValues={setV} onReady={setReady} disabled={busy}/>{ready&&<><div className="form-grid"><label>Total bonus budget<select value={quiz.total} onChange={e=>setQuiz({...quiz,total:e.target.value})}><option value="">Select</option><option value="100">100 units</option><option value="1000">1,000 units</option></select></label><label>Who receives the bonus?<select value={quiz.self} onChange={e=>setQuiz({...quiz,self:e.target.value})}><option value="">Select</option><option value="included">Myself and four other members</option><option value="excluded">Only the four other members</option></select></label></div><button disabled={busy||!quiz.total||!quiz.self} onClick={prepare}>Check and begin</button></>}</section>
 :me.answers.length===4&&!me.bIntroDone?<section className="card narrow"><div className="eyebrow">PART 1 COMPLETE · 4 OF 12 SAVED</div><h2>Departments in the next cases</h2><p>In the following cases, you will also see each member's department. You will be assigned to Department A or B. Two of the other members belong to your department and two to the other department.</p><p>The departments have equal standing. All five people are members of the project. No additional differences in personal relationships or future cooperation are specified.</p><button disabled={busy} onClick={beginB}>Show my department and continue</button></section>
 :me.answers.length<12?<section className="card narrow"><div className="eyebrow">INDIVIDUAL DECISION {me.answers.length+1} / 12</div><h2>Allocate the 1,000-unit bonus.</h2>{me.department&&<p>You belong to <strong>Department {me.department}</strong>. The departments have equal standing; two of the other members are in each department.</p>}<p>You are one of the five recipients. Each case concerns a separate project.</p><details><summary>Review instructions</summary><p>{scenario}</p></details>{me.currentTrial&&<Allocation key={"round"+me.answers.length} rows={me.currentTrial.recipients} department={me.department} values={v} setValues={setV} onReady={setReady} disabled={busy}/>}<button disabled={busy||!ready} onClick={save}>{busy?"Saving…":me.answers.length===11?"Save decision 12":"Save & next decision"}</button><p className="small">Saved decisions cannot be revised. Blank amounts are not treated as zero.</p></section>
 :reasonIndex>=0?<section className="card narrow"><div className="eyebrow">12 DECISIONS SAVED · OPTIONAL EXPLANATION {reasonIndex+1} / 2</div><h2>{reasonRecord.initial===null?"Looking back at one case":"Any other considerations?"}</h2><p>Decision {(reasonCase?.index??0)+1}, selected before you made any allocations.</p>{reasonCase&&<table><thead><tr><th>Member</th><th>Contribution</th><th>Your award</th></tr></thead><tbody>{reasonCase.trial.recipients.map((r:any,i:number)=><tr key={r.id}><th>{r.self?"You":r.id}{reasonCase.trial.block==="B"&&<small> · Dept. {r.self||r.same?me.department:me.department==="A"?"B":"A"}</small>}</th><td>{r.score}</td><td>{reasonCase.awards[i]}</td></tr>)}</tbody></table>}<Field label={reasonRecord.initial===null?"What information did you consider, and how did it affect your allocation in this case?":"If there were other considerations, how did you balance them?"} value={reasonText} setValue={setReasonText}/><button disabled={busy} onClick={()=>run(async()=>{hydrate(await req({action:"reason",case:reasonIndex,followup:reasonRecord.initial!==null,text:reasonText}));setReasonText("");})}>{reasonText.trim()?"Save and continue":"Skip and continue"}</button></section>
 :<section className="card narrow"><div className="eyebrow">FINAL STEP · OPTIONAL FEEDBACK {Math.min(checkStep+1,9)} / 9</div><h2>{checkStep<8?"About the activity":"Anything missing?"}</h2>{checkStep<8?<Field label={checkItems[checkStep][1]} value={checks[checkItems[checkStep][0]]||""} setValue={x=>setChecks({...checks,[checkItems[checkStep][0]]:x})}/>:<Field label="What information or instructions were missing?" value={needed} setValue={setNeeded}/>}<p className="small">You may skip every question. Your answers do not change whether your decisions are included.</p><div className="buttons">{checkStep>0&&<button className="outline" onClick={()=>setCheckStep(checkStep-1)}>Previous question</button>}{checkStep<8?<button onClick={()=>setCheckStep(checkStep+1)}>Continue</button>:<button disabled={busy} onClick={finish}>Submit my responses</button>}<button className="outline" disabled={busy} onClick={finish}>Skip remaining feedback and submit</button></div></section>)}
 {p===4&&!host&&<section className="card"><p>Automatic updates have stopped at wrap-up.</p><button className="outline" disabled={busy} onClick={refresh}>Check session status</button></section>}
 {p>=2&&<Results stats={s.stats} demo={s.room.demo}/>}
 {p===2&&<section><h2>Discuss the class patterns.</h2><Prompts/><section className="card"><h3>New information for discussion</h3><p>{teamEvidence}</p><p>This team activity follows the individual task. Team answers are stored separately.</p></section>{host?<section className="card"><h3>Representative codes</h3><p>Give each code only to its team representative.</p><div className="team-codes">{s.teamKeys.map((k:string,i:number)=><div key={i}>Team {i+1}<code>{k}</code></div>)}</div><p>{s.teams.length} / {s.room.teamCount} teams submitted</p></section>:<section className="card narrow"><div className="eyebrow">TEAM {me.team} · STEP {teamStep+1} / 5</div>{teamStep<4?<Field label={teamFields[teamStep][1]} value={draft[teamFields[teamStep][0]]} setValue={x=>setDraft({...draft,[teamFields[teamStep][0]]:x})}/>:<><p>For this discussion case, act together as the project member labelled “You”, in Department A. Allocate 1,000 units among all five people.</p><Allocation key="team" rows={teamCase} department="A" values={tv} setValues={setTv} onReady={setTeamReady} disabled={busy}/><Field label="State your allocation principle and reasons." value={draft.principle} setValue={x=>setDraft({...draft,principle:x})}/><label>Representative code<input value={teamKey} onChange={e=>setTeamKey(e.target.value)}/></label></>}<div className="buttons">{teamStep>0&&<button className="outline" onClick={()=>setTeamStep(teamStep-1)}>Previous step</button>}{teamStep<4?<button disabled={!draft[teamFields[teamStep][0]].trim()} onClick={()=>setTeamStep(teamStep+1)}>Next discussion question</button>:<button disabled={busy||!me.submitted||!teamReady||!teamKey||!draft.principle.trim()} onClick={submitTeam}>Save team response</button>}</div>{s.teams.some((t:any)=>t.team===me.team)&&<p>A response is saved for your team.</p>}</section>}</section>}
 {p>=3&&<section><h2>From a pattern to a proposal.</h2>{s.teams.length?s.teams.map((t:any)=><article className="card" key={t.team}><h3>Team {t.team}</h3>{["pattern","explanation","need","actions","principle"].map(k=><p key={k}>{t.payload[k]}</p>)}<p>Allocation: {t.payload.awards.join(" · ")} units</p></article>):<p>No team responses submitted.</p>}<div className="card takeaway"><h3>A reward decision is not a measure of motivation.</h3><p>Allocations show how rewards were divided. They do not show how recipients would respond. We also need evidence about what recipients value and how they interpret the decision.</p></div></section>}
 {!host&&<details className="participant-options"><summary>Participation information & withdrawal</summary><Consent/><p>Your response reference: <code>{me.id}</code></p><button className="outline danger" disabled={busy} onClick={withdraw}>Withdraw and remove my individual responses</button></details>}
 </main>}<footer><span>OB DECISION STUDIO</span><span>Individual choices · Shared evidence · Team discussion</span></footer></>;
}
