import {studyInfo} from "../lib/consent";
import {validAwards,type Recipient} from "../lib/experiment";
const fmt=(v:number|null|undefined)=>v==null?"—":v.toFixed(1);
export function Consent(){return <div className="consent-copy">
<p><strong>Purpose:</strong> To pilot a bonus-allocation task and explore reasoning about rewards after a motivation lesson.</p>
<p><strong>Activity:</strong> Eight fictional bonus decisions, followed by optional questions about income, workplace rewards, political orientation, gender, and your experience. No real bonus payments.</p>
<p><strong>Voluntary choice:</strong> You may decline, stop, or skip opinion and background questions without a grade penalty. A no-record activity is available; you can still join team discussion.</p>
<p><strong>Discomfort:</strong> Political and reward questions may feel personal. Skip them without giving a reason.</p>
<p><strong>Data:</strong> We store a random reference, team number, choices, timing, consent record, and optional answers. Do not enter names or student IDs in free text. Hosting services may process technical connection data. Response combinations may still make someone recognizable; complete anonymity is not promised.</p>
<p><strong>Sharing:</strong> Classmates see allocation summaries after responses close and at least five people finish. Political orientation and background answers are not shown in class. Team discussion text is shared during presentations.</p>
<p><strong>Research use:</strong> Future research use is subject to institutional determination and required procedures, and will use de-identified data only. {studyInfo.status}</p>
<p><strong>Retention:</strong> {studyInfo.retention}</p>
<p><strong>Withdrawal:</strong> Use the withdrawal button to remove individual answers from the active dataset. Contact the researchers with your response reference about downloaded copies. Removal may no longer be possible after irreversible de-identification or aggregation. Team-authored responses are separate.</p>
<p><strong>Researchers:</strong> {studyInfo.researchers}, {studyInfo.institution}. <a href={"mailto:"+studyInfo.email}>{studyInfo.email}</a> · <a href={"tel:"+studyInfo.phone}>{studyInfo.phone}</a></p>
</div>;}
export function Allocation({rows,department,values,setValues}:{rows:Recipient[];department:string;values:string[];setValues:(v:string[])=>void}){const sum=values.reduce((s,v)=>s+(Number(v)||0),0);return <div className="allocation"><table><caption>Contribution total: 100 · Bonus budget: 100 points</caption><thead><tr><th>Member</th><th>Dept.</th><th>Contribution</th><th>Award</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><th>{r.id}</th><td>{r.same?department:department==="A"?"B":"A"}</td><td>{r.score}</td><td><input aria-label={"Award for "+r.id} type="number" inputMode="numeric" min={0} max={100} step={1} placeholder="—" value={values[i]} onChange={e=>{const v=[...values];v[i]=e.target.value;setValues(v);}}/></td></tr>)}</tbody></table><div className="sum" aria-live="polite"><strong>Total {sum} / 100</strong><span>{sum>100?(sum-100)+" over budget":sum<100?(100-sum)+" points remaining":values.some(x=>x==="")?"Enter every amount, including zeros.":validAwards(values.map(Number))?"Total complete":"Use whole numbers from 0 to 100."}</span></div></div>;}
export function Field({label,value,setValue}:{label:string;value:string;setValue:(v:string)=>void}){return <label>{label}<textarea maxLength={1000} value={value} onChange={e=>setValue(e.target.value)} placeholder="Use your own words. Do not enter anyone's name."/></label>;}
export function Prompts(){return <ol className="prompts"><li><strong>Notice.</strong> Identify a pattern using a number from the class summary.</li><li><strong>Explain.</strong> Suggest a reason and an alternative. What can these data not tell us?</li><li><strong>Connect.</strong> Use a motivation theory from the lesson. Distinguish evidence from assumptions about people's needs.</li><li><strong>Act.</strong> Propose two actions beyond pay. How would you check whether motivation improved?</li></ol>;}
export function Results({stats:s,demo}:{stats:any;demo:boolean}){return <section className="results"><div className="eyebrow">{demo?"REHEARSAL RESULTS — NOT RESEARCH DATA":"CLASS RESULTS — INDIVIDUAL RESPONSES"}</div><h2>Our choices, together.</h2>{!s?<div className="card">Results remain hidden until at least five participants finish.</div>:<><div className="metrics"><Metric label="Completed participants" value={String(s.n)} detail={s.decisions+" decisions; people are the independent units"}/><Metric label="Mean department difference" value={fmt(s.mean)} detail="Same-department points minus other-department points"/><Metric label="Median" value={fmt(s.median)} detail="Each person's eight-decision average"/><Metric label="Standard deviation" value={fmt(s.sd)} detail="Variation between participant averages"/></div><div className="results-grid"><article className="card"><h3>Department allocation differences</h3><p className="small">Each person contributes one average. Positive values mean more points to the same department.</p><div className="histogram" role="img" aria-label="Distribution of participant-average department differences">{s.histogram.map((b:any,i:number)=><div key={i}><span>{b.n}</span><i style={{height:Math.max(2,b.n/Math.max(1,...s.histogram.map((x:any)=>x.n))*160)}}/><small>{b.from}</small></div>)}</div><p className="small">20-point bins. The last bin includes +100.</p></article><article className="card"><h3>Allocation patterns</h3>{[["Exactly proportional",s.exact],["Equal: 25 points each",s.equal],["At least one zero award",s.zeros]].map(([label,n])=><div className="pattern" key={String(label)}><span>{label}</span><strong>{(100*Number(n)/s.decisions).toFixed(1)}%</strong><small>{n} / {s.decisions} decisions</small></div>)}<p className="small">Categories may overlap. No pattern is marked as correct.</p></article></div><details className="card"><summary>Mean award by contribution score</summary><table><thead><tr><th>Contribution</th><th>Mean award</th><th>Observations</th></tr></thead><tbody>{Object.entries(s.scores).sort((a,b)=>+a[0]-+b[0]).map(([score,x]:any)=><tr key={score}><td>{score}</td><td>{fmt(x.sum/x.n)}</td><td>{x.n}</td></tr>)}</tbody></table><p className="small">Recipient observations repeat within people and are not independent participants.</p></details><p className="interpretation">These are descriptive allocation results, not tests of political orientation or measures of motivation. No individual response or political subgroup is displayed.</p></>}</section>;}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>;}
