"use client";
import {useState,useEffect,useRef} from "react";
import {studyInfo} from "../lib/consent";
import {validAwards,type Recipient} from "../lib/experiment";
export function Consent(){return <div className="consent-copy"><p><strong>Activity:</strong> Twelve fictional bonus decisions: four without department information, then eight with department information. Allocate 1,000 units among yourself and four other project members.</p><p><strong>Voluntary:</strong> You may decline or stop without a grade penalty. All opinion, background, explanation and feedback questions may be skipped. A no-record activity is available.</p><p><strong>Data:</strong> A random response reference, team, choices, timing, consent, and optional answers are stored. Do not enter names or student IDs. Response combinations may still make someone recognizable.</p><p><strong>Class display:</strong> Only allocation summaries appear after responses close and at least five participants finish. Political and background answers are not shown to classmates. Team discussion responses are separate and shared later.</p><p><strong>Classroom format:</strong> Pre-activity questions and decisions take place on the same day. This is a classroom adaptation of Study 2 v8, not its two-session research procedure. Allocation units are not money; there are no bonus payments or lottery.</p><p><strong>Research use:</strong> {studyInfo.status} Future research use requires the applicable institutional procedures.</p><p><strong>Retention:</strong> {studyInfo.retention}</p><p><strong>Withdrawal:</strong> The withdrawal button removes your individual answers from the active dataset. Keep your response reference to contact the researchers about exported copies; team responses are separate.</p><p><strong>Contact:</strong> {studyInfo.researchers}, {studyInfo.institution}. <a href={"mailto:"+studyInfo.email}>{studyInfo.email}</a> · {studyInfo.phone}</p></div>;}
export function Allocation({rows,department,values,setValues,onReady,disabled=false}:{rows:Recipient[];department:string|null;values:string[];setValues:(v:string[])=>void;onReady?:(v:boolean)=>void;disabled?:boolean}){
 const [step,setStep]=useState(0),input=useRef<HTMLInputElement>(null);const sum=values.reduce((n,x)=>n+(Number(x)||0),0),review=step===rows.length,row=rows[step],valid=values.every(x=>x.trim()!=="")&&validAwards(values.map(Number));
 const current=values[step]??"",currentValid=current.trim()!==""&&Number.isInteger(Number(current))&&Number(current)>=0&&Number(current)<=1000;
 useEffect(()=>{onReady?.(review&&valid);},[review,valid,onReady]);useEffect(()=>{input.current?.focus({preventScroll:true});},[step]);
 return <div className="allocation sequential"><div className="reference-table"><table><caption>Contribution total: 100 · Bonus budget: 1,000 units</caption><thead><tr><th>Member</th>{department&&<th>Department</th>}<th>Contribution</th><th>Your award</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={step===i?"current-member":""}><th>{r.self?"You":r.id}{step===i&&<span className="small"> ← current</span>}</th>{department&&<td>{r.self||r.same?department:department==="A"?"B":"A"}</td>}<td>{r.score}</td><td>{values[i]===""?"—":values[i]}</td></tr>)}</tbody></table></div><div className="sum" aria-live="polite"><strong>Total {sum.toLocaleString()} / 1,000</strong><span>{sum<=1000?(1000-sum).toLocaleString()+" units remaining":(sum-1000).toLocaleString()+" units over budget"}</span></div>{review?<div className="member-input"><h3>Review your allocation</h3><p>{valid?"All five amounts total 1,000. You can save this decision.":"The five amounts must total exactly 1,000. Go back to adjust your entries."}</p><button type="button" className="outline" disabled={disabled} onClick={()=>setStep(0)}>Edit amounts</button></div>:<div className="member-input"><div className="eyebrow">RECIPIENT {step+1} OF {rows.length}</div><label><strong>{row.self?"Your allocation":row.id+" allocation"} (units)</strong><input ref={input} aria-label={"Allocation for "+(row.self?"You":row.id)} type="number" inputMode="numeric" min={0} max={1000} step={1} value={current} placeholder="Enter an amount" disabled={disabled} onChange={e=>{const next=[...values];next[step]=e.target.value;setValues(next);}} onKeyDown={e=>{if(e.key==="Enter"&&currentValid&&!disabled){e.preventDefault();setStep(step+1);}}}/></label><div className="buttons">{step>0&&<button type="button" className="outline" disabled={disabled} onClick={()=>setStep(step-1)}>Previous person</button>}<button type="button" disabled={disabled||!currentValid} onClick={()=>setStep(step+1)}>{step===rows.length-1?"Review allocation":"Next person"}</button></div></div>}</div>;
}
export function Field({label,value,setValue}:{label:string;value:string;setValue:(v:string)=>void}){return <label>{label}<textarea maxLength={1000} value={value} onChange={e=>setValue(e.target.value)} placeholder="Use your own words. Do not enter anyone's name."/></label>;}
export function Prompts(){return <ol className="prompts"><li><strong>Notice.</strong> Describe a pattern using a number from the class summary.</li><li><strong>Explain.</strong> Suggest a reason and an alternative. What can the data not tell us?</li><li><strong>Connect.</strong> Use a motivation theory, distinguishing observations from assumptions.</li><li><strong>Act.</strong> Propose two actions beyond pay and how to check their effects.</li></ol>;}
const fmt=(x:number|null|undefined)=>x==null?"—":x.toFixed(2);
export function Results({stats:s,demo}:{stats:any;demo:boolean}){return <section className="results"><div className="eyebrow">{demo?"REHEARSAL RESULTS":"CLASS RESULTS"} · STUDY 2 ALLOCATION TASK</div><h2>Our choices, together.</h2>{!s?<div className="card">Results remain hidden until at least five participants finish.</div>:<><div className="metrics"><Metric label="Completed participants" value={String(s.n)} detail={s.decisions+" decisions; people are the independent units"}/><Metric label="Department difference · B only" value={fmt(s.mean)} detail="Same-department total minus other-department total, as percentage points of the pool; self excluded"/><Metric label="Median difference · B" value={fmt(s.median)} detail="Each person's eight B decisions averaged"/><Metric label="Standard deviation · B" value={fmt(s.sd)} detail="Variation between participant averages"/></div><div className="card"><h3>Allocation patterns across 12 decisions</h3>{[["Exactly score-proportional",s.exact],["Equal: 200 units each",s.equal],["At least one zero award",s.zeros]].map(([label,n])=><div className="pattern" key={String(label)}><span>{label}</span><strong>{s.decisions?(100*Number(n)/s.decisions).toFixed(1):"0"}%</strong><small>{n} / {s.decisions} decisions</small></div>)}</div><p className="interpretation">Descriptive classroom results. A always precedes B, so differences between the two parts do not establish an effect of department information. Political and personal answers are not displayed. No allocation is labelled correct.</p></>}</section>;}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>;}
