import {createHash,randomBytes,randomInt,timingSafeEqual} from "node:crypto";
import {assignments,aggregate,validAwards,PROTOCOL,CONSENT_VERSION,random,type Trial} from "./experiment";
import type {Store,Stored} from "./storage";
import {Conflict} from "./storage";
export class HttpError extends Error{constructor(message:string,public status=400){super(message);}}
function fail(message:string,status=400):never{throw new HttpError(message,status);}
const hash=(s:string)=>createHash("sha256").update(s).digest("hex");
const secret=()=>randomBytes(32).toString("hex");
const now=()=>new Date().toISOString();
function text(v:unknown,max=1200){if(typeof v!=="string"||v.length>max)fail("Please check the length of your response.");return v.trim();}
type Survey={income:number|null;rewards:number|null;politics:number|null;gender:string|null};
const blankSurvey=():Survey=>({income:null,rewards:null,politics:null,gender:null});
type Room={code:string;title:string;hostHash:string;phase:number;teamCount:number;teamKeys:string[];created:string;protocol:string;includedIds:string[];stats:ReturnType<typeof aggregate>|null;counts:{joined:number;completed:number};closedAt:string|null;demo:boolean;assignmentNext:number;assignmentSeed:number};
export type Person={id:string;tokenHash:string;team:number;department:string|null;trials:Trial[];answers:number[][];timings:number[];prepared:boolean;quizAttempts:number;quizLog:{at:string;passed:boolean;total:unknown;self:unknown}[];submitted:boolean;created:string;finished:string|null;consent:{version:string;at:string};reflection:{reason:string;needed:string};survey:Survey;surveyOrder:string[];surveyPosition:string;baselineAt:string|null;preSurveyDone:boolean;bIntroDone:boolean;bStartedAt:string|null;withdrawn:boolean;assignmentTicket:number;assignmentCell:number;seed:number;reasonIndices:number[];reasons:{initial:string|null;followup:string|null}[];checks:Record<string,unknown>;revision:number};
const prefix="ob-study2-v8/";
const roomPath=(c:string)=>prefix+c+"/room.json";
const personPath=(c:string,h:string)=>prefix+c+"/people/"+h+".json";
const teamPath=(c:string,n:number)=>prefix+c+"/teams/"+n+".json";
export function assignmentCell(ticket:number,seed:number){const rng=random((seed+Math.floor(ticket/18))>>>0),cells=Array.from({length:18},(_,i)=>i);for(let i=17;i>0;i--){const j=Math.floor(rng()*(i+1));[cells[i],cells[j]]=[cells[j],cells[i]];}return cells[ticket%18];}
function publicTrial(t:Trial,department:string|null){return{id:t.id,block:t.block,recipients:t.recipients.map(x=>({id:x.id,score:x.score,self:x.self,same:t.block==="B"?x.same:null})),department:t.block==="B"?department:null};}
function surveyInput(s:any):Survey{for(const k of ["income","rewards","politics"]){if(s[k]!=null&&(!Number.isInteger(s[k])||s[k]<1||s[k]>10))fail("Optional scales must be 1–10 or skipped.");}if(![null,undefined,"male","female","another","prefer_not"].includes(s.gender))fail("Check the gender option.");return{income:s.income??null,rewards:s.rewards??null,politics:s.politics??null,gender:s.gender==="prefer_not"?null:s.gender??null};}
export class Classroom {
 constructor(public store:Store,public hostKey:string,public ready=true){}
 async room(code:unknown){const c=text(code,16).toUpperCase();if(!/^[A-F0-9]{8}$/.test(c))fail("Enter a valid class code.",404);const r=await this.store.read<Room>(roomPath(c));if(!r){const old=await this.store.read("ob-v3/"+c+"/room.json");if(old)fail("This is an earlier 8-decision classroom. Ask your instructor for a new Study 2 class code. Earlier responses are preserved.",409);fail("Class not found. Check the code with your instructor.",404);}return r;}
 async person(r:Room,token:string){if(!token)fail("Join the class first.",401);const p=await this.store.read<Person>(personPath(r.code,hash(token)));if(!p||p.value.withdrawn)fail("This access is not active. Please join or contact the instructor.",401);return p;}
 isHost(r:Room,t:string){return !!t&&hash(t)===r.hostHash;}
 async people(r:Room){const keys=await this.store.keys(prefix+r.code+"/people/"),found:Person[]=[];for(let i=0;i<keys.length;i+=12){const xs=await Promise.all(keys.slice(i,i+12).map(k=>this.store.read<Person>(k)));found.push(...xs.filter((x):x is Stored<Person>=>!!x).map(x=>x.value).filter(p=>!p.withdrawn));}return found;}
 async teams(r:Room){const keys=await this.store.keys(prefix+r.code+"/teams/");return(await Promise.all(keys.map(k=>this.store.read<{team:number;payload:Record<string,unknown>}>(k)))).filter(x=>!!x).map(x=>x!.value).sort((a,b)=>a.team-b.team);}
 async snapshot(code:unknown,t:string){const r=(await this.room(code)).value,host=this.isHost(r,t),p=host?null:(await this.person(r,t)).value,teams=await this.teams(r);
 let counts=r.counts;if(host&&r.phase<=1){const ps=await this.people(r);counts={joined:ps.length,completed:ps.filter(x=>x.submitted).length};}
 const current=p&&p.prepared&&!p.submitted&&p.answers.length<12&&(p.answers.length<4||p.bIntroDone)?publicTrial(p.trials[p.answers.length],p.department):null;
 return{room:{code:r.code,title:r.title,phase:r.phase,teamCount:r.teamCount,protocol:r.protocol,demo:r.demo,mode:"classroom_same_day"},isHost:host,counts,stats:r.phase>=2&&r.stats&&r.stats.n>=5?r.stats:null,suppressed:r.phase>=2&&(!r.stats||r.stats.n<5),teamKeys:host?r.teamKeys:undefined,
 me:p?{id:p.id,team:p.team,department:p.answers.length>=4?p.department:null,currentTrial:current,answers:p.answers,prepared:p.prepared,submitted:p.submitted,reflection:p.reflection,survey:p.survey,consent:p.consent,preSurveyDone:p.preSurveyDone,surveyOrder:p.surveyOrder,bIntroDone:p.bIntroDone,revision:p.revision,reasons:p.reasons,checks:p.checks,reasonCases:p.answers.length===12?p.reasonIndices.map(i=>({index:i,trial:publicTrial(p.trials[i],p.department),awards:p.answers[i]})):[]}:null,
 teams:r.phase>=3?teams:teams.filter(x=>host||x.team===p?.team).map(x=>host?{team:x.team}:x)};
 }
 async action(b:Record<string,any>,t:string){
 if(b.action==="create"){const key=typeof b.hostKey==="string"?b.hostKey:"",a=Buffer.from(key),expected=Buffer.from(this.hostKey);if(!expected.length||a.length!==expected.length||!timingSafeEqual(a,expected))fail("Enter the instructor key.",401);if(!Number.isInteger(b.teamCount)||b.teamCount<1||b.teamCount>22)fail("Choose 1 to 22 teams.");
 const code=randomBytes(4).toString("hex").toUpperCase(),credential=secret(),r:Room={code,title:text(b.title,80)||"Motivation & Allocation",hostHash:hash(credential),phase:0,teamCount:b.teamCount,teamKeys:Array.from({length:b.teamCount},()=>randomBytes(4).toString("hex")),created:now(),protocol:PROTOCOL,includedIds:[],stats:null,counts:{joined:0,completed:0},closedAt:null,demo:b.demo===true,assignmentNext:0,assignmentSeed:randomInt(0x100000000)};
 await this.store.write(roomPath(code),r);return{credential,...await this.snapshot(code,credential)};}
 let row=await this.room(b.code),r=row.value;
 if(b.action==="join"){if(!this.ready&&!r.demo)fail("The participation information is not yet complete. Please wait for your instructor.",409);if(r.phase>1)fail("Individual responses have closed.",409);if(b.consent!==true||b.consentVersion!==CONSENT_VERSION)fail("Voluntary consent is required to join. You may choose the no-record activity instead.",403);if(!Number.isInteger(b.team)||b.team<1||b.team>r.teamCount)fail("Check your team number.");
 let ticket=-1;for(let attempt=0;attempt<24;attempt++){row=await this.room(r.code);r=row.value;if(r.phase>1)fail("Individual responses have closed.",409);try{ticket=r.assignmentNext;await this.store.write(roomPath(r.code),{...r,assignmentNext:ticket+1},row.etag);break;}catch(e){if(!(e instanceof Conflict)||attempt===23)throw e;await new Promise(resolve=>setTimeout(resolve,20+randomInt(80)));}}
 const credential=secret(),h=hash(credential),seed=randomInt(0x100000000),cell=assignmentCell(ticket,r.assignmentSeed),p:Person={id:randomBytes(8).toString("hex"),tokenHash:h,team:b.team,department:null,trials:assignments(seed,cell),answers:[],timings:[],prepared:false,quizAttempts:0,quizLog:[],submitted:false,created:now(),finished:null,consent:{version:CONSENT_VERSION,at:now()},reflection:{reason:"",needed:""},survey:blankSurvey(),surveyOrder:randomInt(2)?["income","rewards"]:["rewards","income"],surveyPosition:"same_day_before_practice_classroom_adaptation_not_formal_T0",baselineAt:null,preSurveyDone:false,bIntroDone:false,bStartedAt:null,withdrawn:false,assignmentTicket:ticket,assignmentCell:cell,seed,reasonIndices:[randomInt(4),4+randomInt(8)],reasons:[{initial:null,followup:null},{initial:null,followup:null}],checks:{},revision:0};
 await this.store.write(personPath(r.code,h),p);return{credential,...await this.snapshot(r.code,credential)};}
 const host=this.isHost(r,t);
 if(b.action==="phase"){if(!host)fail("Instructor access required.",403);if(b.phase!==r.phase+1||b.phase>4)fail("Advance one stage at a time.",409);
 if(r.phase===1){const ps=await this.people(r),done=ps.filter(p=>p.submitted);r={...r,closedAt:now(),includedIds:done.map(p=>p.id),stats:aggregate(done),counts:{joined:ps.length,completed:done.length}};}
 r.phase=b.phase;await this.store.write(roomPath(r.code),r,row.etag);return this.snapshot(r.code,t);}
 if(b.action==="export"){if(!host)fail("Instructor access required.",403);if(r.phase<2)fail("Close individual responses before exporting.",409);const ps=await this.people(r);return{protocol:r.protocol,consentVersion:CONSENT_VERSION,exportedAt:now(),classCode:r.code,mode:"classroom_same_day",measurementTiming:"Same-day pre-allocation questions; not formal T0 3–7 days before T1.",paymentMode:"No bonus payments or lottery in this classroom activity.",allocationUnits:1000,recipientCount:5,trialCount:12,formalStudy2MainSample:false,assignment:{reserved:r.assignmentNext,joined:ps.length,cells:Array.from({length:18},(_,cell)=>({cell,joined:ps.filter(p=>p.assignmentCell===cell).length,completed:ps.filter(p=>p.assignmentCell===cell&&p.submitted).length}))},participants:ps.map(({tokenHash,...p})=>({...p,inClassSummary:r.includedIds.includes(p.id)})),teams:await this.teams(r),summary:r.stats};}
 if(host)fail("Use a student session for participant actions.",403);
 const pr=await this.person(r,t),p=pr.value,key=personPath(r.code,p.tokenHash);
 const persist=async()=>{p.revision++;await this.store.write(key,p,pr.etag);};
 if(b.action==="withdraw"){p.withdrawn=true;p.answers=[];p.trials=[];p.timings=[];p.reflection={reason:"",needed:""};p.survey=blankSurvey();p.reasons=[];p.checks={};await persist();for(let attempt=0;attempt<8;attempt++){const rr=await this.room(r.code);if(rr.value.phase<2)break;const ps=(await this.people(rr.value)).filter(x=>rr.value.includedIds.includes(x.id));try{await this.store.write(roomPath(r.code),{...rr.value,includedIds:ps.map(x=>x.id),stats:aggregate(ps),counts:{...rr.value.counts,completed:ps.length}},rr.etag);break;}catch(e){if(!(e instanceof Conflict)||attempt===7)throw e;}}return{withdrawn:true};}
 if(b.action==="team"){if(r.phase!==2)fail("Team responses are open only during discussion.",409);if(!p.submitted)fail("A participant who finished the individual task must submit for the team.");if(b.teamKey!==r.teamKeys[p.team-1])fail("Check the representative code.",403);const x=b.payload;if(!x||!validAwards(x.awards))fail("The five team allocations must total 1,000 units.");const payload={awards:x.awards,pattern:text(x.pattern),explanation:text(x.explanation),need:text(x.need),actions:text(x.actions),principle:text(x.principle)};if(Object.entries(payload).some(([k,v])=>k!=="awards"&&!v))fail("Complete the team discussion fields.");const tk=teamPath(r.code,p.team),prior=await this.store.read(tk);await this.store.write(tk,{team:p.team,payload,updated:now(),task:"classroom_discussion_not_individual_study2"},prior?.etag);return this.snapshot(r.code,t);}
 if(r.phase!==1)fail("Individual responses are not open.",409);
 if(p.submitted){if(b.action==="finish")return this.snapshot(r.code,t);fail("These responses have already been submitted.",409);}
 if(b.action==="baseline"){if(p.preSurveyDone)fail("Pre-activity answers are already saved.",409);p.survey=surveyInput(b.survey||{});p.preSurveyDone=true;p.baselineAt=now();await persist();return this.snapshot(r.code,t);}
 if(!p.preSurveyDone)fail("Complete or skip the pre-activity questions first.",409);
 if(b.action==="prepare"){if(p.prepared)return this.snapshot(r.code,t);if(!validAwards(b.awards))fail("Enter five whole numbers totaling 1,000 units.");p.quizAttempts++;p.prepared=b.total===1000&&b.self==="included";p.quizLog.push({at:now(),passed:p.prepared,total:b.total??null,self:b.self??null});await persist();return{...await this.snapshot(r.code,t),feedback:p.prepared?"Practice complete. Start decision 1 of 12.":"The budget is 1,000 units, and you are one of the five recipients. Please check and try again."};}
 if(!p.prepared)fail("Complete the practice first.",409);
 if(b.action==="beginB"){if(p.answers.length!==4)fail("Complete the first four decisions first.",409);if(!p.bIntroDone){p.department=randomInt(2)?"A":"B";p.bIntroDone=true;p.bStartedAt=now();await persist();}return this.snapshot(r.code,t);}
 if(b.action==="round"){if(!Number.isInteger(b.index)||b.index<0||b.index>=12)fail("Check the decision number.");if(!validAwards(b.awards))fail("Enter five whole numbers totaling 1,000 units.");
 if(b.index<p.answers.length){if(JSON.stringify(b.awards)===JSON.stringify(p.answers[b.index]))return this.snapshot(r.code,t);fail("This decision is already saved and cannot be changed.",409);}
 if(b.index!==p.answers.length)fail("Save decisions in order.",409);if(b.index>=4&&!p.bIntroDone)fail("Read the department instructions before continuing.",409);
 p.answers.push(b.awards);p.timings.push(typeof b.elapsedMs==="number"&&Number.isFinite(b.elapsedMs)?Math.max(0,Math.min(86400000,b.elapsedMs)):0);await persist();return this.snapshot(r.code,t);}
 if(p.answers.length!==12)fail("Complete all twelve decisions first.",409);
 if(b.action==="reason"){const i=b.case;if(i!==0&&i!==1)fail("Check the selected case.");const field=b.followup?"followup":"initial";if(field==="followup"&&p.reasons[i].initial===null)fail("Save or skip the first explanation first.");if(p.reasons[i][field]!==null)fail("This explanation has already been saved.",409);p.reasons[i][field]=text(b.text??"",1500);await persist();return this.snapshot(r.code,t);}
 if(b.action==="finish"){if(p.reasons.some(x=>x.initial===null||x.followup===null))fail("Complete or skip the two case explanations first.",409);const checks=b.checks||{};const allowed=["scoreMeaning","ownDepartment","otherDepartment","equalStanding","discretion","repetition","expectation","relationships"];p.checks=Object.fromEntries(allowed.map(k=>[k,text(checks[k]??"",1000)]));p.reflection={reason:text(b.reason??"",1500),needed:text(b.needed??"",1000)};p.submitted=true;p.finished=now();await persist();const after=(await this.room(r.code)).value;if(after.phase>=2&&!after.includedIds.includes(p.id))fail("The class closed before this submission was included. Please tell your instructor.",409);return this.snapshot(r.code,t);}
 fail("Unsupported action.");
 }
}
